import type { Metadata } from "next";

import type { Locale } from "../supportedLocales";

import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Awesome News",
  description: "Generated by JoG",
};

type LocaleLayoutProps = {
  children: React.ReactNode;
  params: { locale: Locale };
};

export default function LocaleLayout({
  children,
  params: { locale },
}: LocaleLayoutProps) {
  return (
    <html lang={locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
