import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import type { ReactNode } from "react";

import type { Locale } from "@/supportedLanguages";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Awesome News",
  description: "Generated by JoG",
};

type RootLayoutProps = {
  children: ReactNode;
  params: { locale: Locale };
};

export default function RootLayout({
  children,
  params: { locale },
}: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body
        className={`${inter.className} mx-auto flex min-h-dvh max-w-5xl animate-fadeIn flex-col`}
      >
        {children}
      </body>
    </html>
  );
}
